export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const SAVE_POSTS_BY_CATEGORY = 'SAVE_POSTS_BY_CATEGORY';
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const SAVE_POST = 'SAVE_POST';
